### ISSUE TITLE
Vaccine Loop

### ISSUE THREAD

**Issue by mlberg** [OpenSRP/opensrp-unicef-wcaro#119] opened 2019-02-14 17:26 UTC
Right now the app forces you say a child was vaccinatied. If you get to the end and don't check yellow fever, etc it doesn't allow you to submit the visit form.

We have to remember CHWs don't give vaccines.  they can only record if a child received it or not so their job is primarily as a record keeper for this (with the idea that they refer)/ . So we need to be able to record if the child hasn't received vaccines.

This should probably be given priority over a lot of of the other issues as it will block CHWs from properly completing visits.

<img width="616" alt="screen shot 2019-02-14 at 12 18 58 pm" src="https://user-images.githubusercontent.com/42673455/52805156-f9a0e200-3053-11e9-8c7d-c2493b3f6785.png">

<img width="614" alt="screen shot 2019-02-14 at 12 18 51 pm" src="https://user-images.githubusercontent.com/42673455/52805138-f4dc2e00-3053-11e9-8659-bc3fa9761ba9.png">

**Comment by cagulas** [comment] 2019-02-15 10:16
@mberg In testing this quite a few times, I think the reason this is happening is that you're unchecking the vaccines. What we'll need to do is introduce logic to make sure that if they unchecked all vaccines, they can't press either button at the bottom. But I think that's what the issue is here.

**Comment by raihan-mpower** [comment] 2019-02-15 11:05
@cagulas right now handled this issue as whenever someone unchecked the vaccine, we are considering it as not given

**Comment by cagulas** [comment] 2019-02-15 11:05
Ok, I think that should work for now.

**Comment by raihan-mpower** [comment] 2019-02-15 12:51
fixed in #126

**Comment by cagulas** [comment] 2019-02-20 09:14
Closing this and creating new issues for vaccine widget interactions after our discussions today.

**Closed by cagulas** 2019-02-20 09:14 UTC
Labels: bug, high priority
